config/routes.rb
GatorAID::Application.routes.draw do

  resources :activities

  match '/text_geocoder' => 'text_geocoder#geocode'

  root :to => 'pages#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	attr_accessible :country, :description, :identifier, :title, :marker_color, :precision

	has_many :positions

	after_create :generate_random_color

	def generate_random_color
		if precision == "country"
			self.marker_color = "000000"
		else
			self.marker_color = "%06x" % (rand * 0xffffff)
		end
		
		self.save
	end
end

app/models/position.rb
class Position < ActiveRecord::Base
	belongs_to :activity
	attr_accessible :lat, :long, :keyword, :address

	acts_as_gmappable lat: "lat", lng: "long", process_geocoding: false

	def gmaps4rails_infowindow
		"""#{activity.identifier} <br>
		#{activity.description} <br>
		#{keyword} <br>
		#{address} <br>
		<a href='/activities/#{activity.id}'>Details</a>
		""".html_safe
	end

	def gmaps4rails_marker_picture
		{
			:picture => "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|#{activity.marker_color}",
			:shadow_picture => "http://chart.apis.google.com/chart?chst=d_map_pin_shadow",
			:width   => 21,
			:height  => 43,
			:marker_anchor => [10, 34],
			:shadow_width => "40",
			:shadow_height => "37",
			:shadow_anchor => [12, 35]
		}
	end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	require 'json'

	def index
		@activities = Activity.all
	end

	def show
		@activity = Activity.find params[:id]
		@json = @activity.positions.to_gmaps4rails
	end

	def new
		@activity = Activity.new
	end

	def create
		contents = params["iati_xml"]
		@activities = JSON.parse params["activities_with_geocode"]

		@activities.delete(@activities.last)

		@activities.each do |activity|
			activity_obj = Activity.find_by_identifier activity["uid"]
			if activity_obj.nil?
				activity_obj = Activity.create(identifier: activity["uid"], precision: activity["precision"])

				activity["positions"].each do |position|
					activity_obj.positions << Position.create(lat: position["latitude"].to_f, long: position["longitude"].to_f, address: position["address"])
				end

			end
		end

		response = Nokogiri::XML(contents)

		# loop each activity
		response.xpath("//iati-activity").each do |activity|

			# get iati-identifier
			iati_id = activity.at("iati-identifier").text

			# store recipient country 
			rcpt_country = activity.at("recipient-country")
			
			# eliminate records with multi country data
			if rcpt_country and rcpt_country.attr("percentage") == "100"

				# find country name
				country = IsoCountryCodes.find(rcpt_country.attr("code")).name

				# loop each description in activities
				Nokogiri::XML(activity.to_s).xpath("//description").each do |desc|

					# find the correct and English description 
					if desc.attr("type") and desc.attr("xml:lang") == "en"

						activity_obj = Activity.find_by_identifier iati_id

						if activity_obj
							activity_obj.update_attributes(description: desc.text, country: country)
							activity_obj.save
						end
					end
				end
			end
		end # end of loop

		redirect_to :root

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@json = Position.all.to_gmaps4rails
	end
end

app/controllers/text_geocoder_controller.rb
class TextGeocoderController < ApplicationController
	require 'open-uri'
	require 'text_geocoder'

	def geocode
		
		# get params
		# call gem with text

		@activities_with_geocode = TextGeocoder::geocode(params["contents"])

		respond_to do |format|
			format.html
			format.json { render json: @activities_with_geocode }
		end

	end

	def test
	end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/text_geocoder_helper.rb
module TextGeocoderHelper
end

app/views/activities/index.html.erb
<div class="page-header">
	<h1>All Activities</h1>
</div>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Activity ID</th>
			<th>Desc</th>
			<th>Country</th>
			<th>Type</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @activities.each do |activity| %>
		<tr>
			<td><%= activity.identifier %></td>
			<td><%= activity.description %></td>
			<td><%= activity.country %></td>
			<td><%= activity.precision %></td>
			<td><%= link_to "Details", activity_path(activity), class: "btn" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/activities/new.html.erb
<div class="page-header">
	<h1>Import IATI XML Data</h1>
</div>
<%= form_for @activity, multipart: true, html: {class: "form-horizontal"} do |f| %>
<%= hidden_field_tag :activities_with_geocode %>
<div class="control-group hide">
	<label class="control-label" for="iati_xml">XML</label>
	<div class="controls">
		<%= text_area_tag :iati_xml, nil, rows: "18" %>
	</div>
</div>
<div class="control-group hide">
	<div class="controls">
		<%= button_to_function "Create", "geocode()", class: "btn" %>
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="iati_xml_file">Select XML File</label>
	<div class="controls">
		<%= file_field_tag :iati_xml_file %>
	</div>
</div>
<div class="control-group">
	<div class="controls">
		<%= button_to_function "Upload", "filereader()", class: "btn" %>
	</div>
</div>

<%= image_tag("loading.gif", class: "hidden", id: "loading_indicator") %>

<% end %>


<script type="text/javascript">
function geocode(iati_xml) {

	if (typeof iati_xml == "undefined") {
		iati_xml = $("#iati_xml").val();	
	}

	$.ajax({
		url: "/text_geocoder.json",
		type: "POST",
		data: {"contents": iati_xml},
		beforeSend: function() {
			$('#loading_indicator').removeClass("hidden");
		},
		success: function(data) {
			$("#activities_with_geocode").val(JSON.stringify(data));
			$('form').submit();
		}
	});

}

function filereader() {

	if (window.File && window.FileReader && window.FileList && window.Blob) {

	} else {
		alert('The File APIs are not fully supported in this browser.');
		return;
	}   

	input = document.getElementById('iati_xml_file');
	if (!input) {
		alert("Um, couldn't find the fileinput element.");
	}
	else if (!input.files) {
		alert("This browser doesn't seem to support the `files` property of file inputs.");
	}
	else if (!input.files[0]) {
		alert("Please select a file before clicking 'Load'");               
	}
	else {
		file = input.files[0];
		fr = new FileReader();
		fr.onload = receivedText;
		fr.readAsText(file);
	}
}

function receivedText() {           
	geocode(fr.result);
	$("#iati_xml").val(fr.result);
}

</script>

app/views/activities/show.html.erb
<div class="page-header">
	<h1>Activity <%= @activity.identifier %></h1>
</div>

<%= gmaps(map_options: {zoom: 2, auto_adjust: false}, markers: { data: @json, options: { do_clustering: true, clusterer_maxZoom: 2 } }) %>

<br>

<h3>Activity Locations</h3>

<div class="span8">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th></th>
				<th>Lat, Long</th>
				<th>Keyword</th>
				<th>Address</th>
			</tr>
		</thead>
		<tbody>
			<% @activity.positions.each_with_index do |position, index| %>
			<tr>
				<td><%= index+1 %></td>
				<td><%= "#{position.lat}, #{position.long}" %></td>
				<td><%= position.keyword %></td>
				<td><%= position.address %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>GatorAID</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Home", :root, class: "brand" %>
				<div class="container">
					<ul class="nav">
						<li><%= link_to "Import IATI XML Data", new_activity_path %></li>
						<li><%= link_to "All Activities", activities_path %></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<div id="main" role="main">
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="span12">
						<%= render 'layouts/messages' %>
						<%= yield %>
					</div>
				</div>
			</div>
		</div> <!--! end of .container -->
	</div> <!--! end of #main -->

	<footer>
		<%= yield :scripts %>
	</footer>

</body>
</html>

app/views/pages/index.html.erb
<div class="span12">
	<%= gmaps(map_options: {zoom: 3, auto_adjust: false}, markers: { data: @json, options: { do_clustering: true, clusterer_maxZoom: 2 } }) %>
</div>

app/views/text_geocoder/geocode.html.erb
<%= @activities_with_geocode %>

app/views/text_geocoder/test.html.erb
<%= form_tag '/activities', multipart: true, html: {class: "form-horizontal"} do %>
<label for="file">File to Upload</label> <%= file_field_tag "file" %>
<%= button_to_function "Create", "filereader()", class: "btn" %>
<% end %>

<div id="editor"></div>

<script type="text/javascript">

function filereader() {

	if (window.File && window.FileReader && window.FileList && window.Blob) {

	} else {
		alert('The File APIs are not fully supported in this browser.');
		return;
	}   

	input = document.getElementById('file');
	if (!input) {
		alert("Um, couldn't find the fileinput element.");
	}
	else if (!input.files) {
		alert("This browser doesn't seem to support the `files` property of file inputs.");
	}
	else if (!input.files[0]) {
		alert("Please select a file before clicking 'Load'");               
	}
	else {
		file = input.files[0];
		fr = new FileReader();
		fr.onload = receivedText;
		fr.readAsText(file);
	}
}

function receivedText() {           
	document.getElementById('editor').appendChild(document.createTextNode(fr.result))
}  

</script>
